### ISSUE TITLE
Spade tenant app spec

### ISSUE THREAD

**Issue by xmcai2016** [data-preservation-programs/spade#12]
ETA: 2023-09-20

The spec to be reviewed is on [Notion](https://www.notion.so/ecosystem-wg/Spade-Tenant-App-4f311af1171248f8b7074f7ec03cf1c0?pvs=4), all comments should be left on Notion.

**Comment by anjor** [comment]
@xmcai2016 this is marked as done in status, but the issue is still open. Do we need to close it?
