### ISSUE TITLE
w3up integration

### ISSUE THREAD

**Issue by xmcai2016** [data-preservation-programs/spade#30]
w3up needs the following: 

- [riba is on this] You can poll our S3 bucket, reads aggregate offers that we write there and establish deals with SPs (being you responsible for signing for this first iteration) 

- [stephen/json?] Enable SPs to read individual pieces instead of the full aggregate bytes (like with dagcargo). As agreed, we are going to give you and endpoint that can be used together with pieceCids, something like pieces.web3.storage/{pieceCid} and they must be able to rely on that endpoint to read all the pieces in the aggregate that were offered

https://filecoinproject.slack.com/archives/C05C7CUPEKX/p1695298925772479?thread_ts=1694081295.454399&cid=C05C7CUPEKX

**Comment by olizilla** [comment]
> Enable SPs to read individual pieces instead of the full aggregate bytes (like with dagcargo)... endpoint that can be used together with pieceCids

Use `https://roundabout.web3.storage/${v2 Piece CID}` – We upgraded the existing `roundabout` endpoint so you can ask it for CAR by v2 PieceCID in https://github.com/web3-storage/w3infra/pull/233

It will provide a redirect to a pre-signed url to the CAR in the bucket, as before, but now it can handled CAR CIDs and Piece CIDs.

**Comment by xmcai2016** [comment]
@ribasushi estimates the second bullet item to be 1 week of work

**Comment by xmcai2016** [comment]
@ribasushi re-assigning this back to you as Stephen's part is complete.
