### ISSUE TITLE
Retrieval Bot - Add support for multiple challenges per level

### ISSUE THREAD

**Issue by jcace** [data-preservation-programs/spade#34]
- Currently the Spade Retrieval bot just does one challenge (link) per level of the tree
- modify it so we can parameterize # of challenges to do per level, to get more coverage of the tree with each retrieval test
- for example, with a `MaxDepth` of `3`, we could do `4` cids at the top level, then `2` cids for each of those at the intermediate level, then `1` cid at the bottom level, resulting in `8` data CIDs tested total (with 16 total bitswap retrievals performed)

**Comment by stephen-pl** [comment]
Do you envision this as a env variable? or something that randomly picked for each run, say a number between 0-10 @jcace

**Comment by jcace** [comment]
@stephen-pl 

Technically, longer term this will be controlled by the specific Tenant and how "stringent" they want to be about their retrieval testing. But, for now let's make this an environment variable that applies to all tests since we don't have that Tenant side built out yet.

**Comment by stephen-pl** [comment]
https://github.com/data-preservation-programs/SpadeRetrievalBot/pull/10
