### ISSUE TITLE
Retrieval Bot: Fix linter issues in SpadeRetrievalBot Repo

### ISSUE THREAD

**Issue by stephen-pl** [data-preservation-programs/spade#41]
In order to set up the build pipeline we can either ignore issues or fix them. I am going to fix them so we can start the project in a good state.

https://github.com/data-preservation-programs/SpadeRetrievalBot/pull/3

**Comment by stephen-pl** [comment]
[https://github.com/data-preservation-programs/SpadeRetrievalBot/pull/3](url)

**Comment by jcace** [comment]
completed
