### ISSUE TITLE
Tenant Service - Baseline & Schema set up

### ISSUE THREAD

**Issue by jcace** [data-preservation-programs/spade#48]
- Set up the Go project structure and baseline schema 
ETA: 2023-10-15

**Comment by xmcai2016** [comment]
Database schema for tenant service, including tenant policies and collections.

**Comment by anjor** [comment]
This is on hold until @jcace comes back from vacation, followed by fil-vegas -- Oct 7.

**Comment by xmcai2016** [comment]
Rough draft is complete on main branch, need finalization.
