### ISSUE TITLE
Spade oracle has real-time source of truth on all sector states 

### ISSUE THREAD

**Issue by xmcai2016** [data-preservation-programs/spade#6]
ETA: 2024-02-29

- sqlite dumps on sector state across the network
- dependency for MPL50 in observing chain state and enabling deal proposing
- nv21 will require investment here in oct/nov
(rebranding from “Deals Oracle” - change in scope due to FIP to remove deals on Filecoin) 
```[tasklist]
### Tasks
- [ ] https://github.com/data-preservation-programs/spade/issues/13
- [ ] https://github.com/data-preservation-programs/spade/issues/21
```

**Comment by anjor** [comment]
This will probably be more than just spade oracle, and a more general oracle, no?

cc: @jlogelin

**Comment by xmcai2016** [comment]
Linking references re: DDO for context.
https://github.com/filecoin-project/FIPs/discussions/730
https://github.com/filecoin-project/lotus/issues/11249
https://filecoinproject.slack.com/archives/C05M7U7L648/p1693966883720379

**Comment by xmcai2016** [comment]
Spade user story: every ~2 hours I want to see the state and metadata of every sector on Filecoin today.

**Comment by xmcai2016** [comment]
Expected consumers of the Oracle: 
- Retrieval Bot v2
- Singularity
- Fil+ CID checker
- filecoin-tracker.com
- Dashboards owned by Network Growth
- and of course, Spade itself

**Comment by xmcai2016** [comment]
@jlogelin to add expected dev tasks to the tasklist above after spec is finalized.

**Comment by jcace** [comment]
closing - out of scope as we'll use the one bundled as part of spade broker for now.
