### ISSUE TITLE
Ground Control Reputation Service ingests SP location data 

### ISSUE THREAD

**Issue by xmcai2016** [data-preservation-programs/spade#8]
ETA: 2023-11-30

**Comment by xmcai2016** [comment]
consume from the SP Reputation WG database for retrieval and location stats: https://data-programs.gitbook.io/reputation/overview/what-is-sp-reputation-wg

**Comment by xmcai2016** [comment]
Marking as complete as our reputation db can be consumed at any time for kentik and retrieval bot stats. Future predicative endeavors are tracked in another backlog item.

**Comment by xmcai2016** [comment]
For Spade: 
- Postgres database that keeps track of the current eligible (tenant, sp) mappings 
- Real-time source of truth on eligibility 
- Ongoing updates according to the GC KYSP results
- One-off updates to include new tenant requirements

**Comment by jcace** [comment]
Closing in favour of https://github.com/data-preservation-programs/spade/issues/45
